[package]
name = "kvs"
author = ["Musaki <musxaki@protonmail.com>"]
description = "CLI Key Value Store"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive", "cargo"] }

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"